-- ===========================================================================
-- Seed catalogue: 14 destinations with galleries, attractions and guides.
-- Imagery is served by Unsplash CDN with sizing parameters applied per use.
-- ===========================================================================

INSERT INTO destinations (name, slug, country, city, region, continent, short_description, description,
                          hero_image_url, thumbnail_url, rating, review_count, popularity_score,
                          best_time_to_visit, average_budget, currency, latitude, longitude, tags,
                          featured, active, created_at, updated_at, created_by, updated_by, version)
VALUES
('Bali', 'bali', 'Indonesia', 'Denpasar', 'Bali', 'Asia',
 'Emerald rice terraces, clifftop temples and beach clubs that glow at sunset.',
 'Bali blends spiritual calm with barefoot luxury. Mornings begin among the terraced paddies of Ubud, afternoons drift through water temples mirrored in still lagoons, and evenings end on the cliffs of Uluwatu where the Indian Ocean turns copper. Beyond the beaches you will find volcano sunrises at Mount Batur, waterfalls hidden in jungle ravines, and a food scene that runs from warung to world class.',
 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1920&q=80',
 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=800&q=80',
 4.80, 2841, 98, 'April to October', 85000.00, 'INR', -8.4095178, 115.1889305,
 'Beach,Luxury,Honeymoon,Culture,Wellness', b'1', b'1',
 UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 'system', 'system', 0),

('Maldives', 'maldives', 'Maldives', 'Male', 'North Male Atoll', 'Asia',
 'Overwater villas above a lagoon so clear the reef reads like stained glass.',
 'The Maldives is the shorthand every traveller uses for perfect water. Twenty-six coral atolls scatter across the Indian Ocean, each ringed by sandbanks that appear and vanish with the tide. Days are spent snorkelling reef walls, drifting with manta rays, and watching bioluminescent plankton light the shallows after dark. It remains the definitive honeymoon destination, and the seaplane transfer is half the experience.',
 'https://images.unsplash.com/photo-1512100356356-de1b84283e18?auto=format&fit=crop&w=1920&q=80',
 'https://images.unsplash.com/photo-1512100356356-de1b84283e18?auto=format&fit=crop&w=800&q=80',
 4.90, 1976, 96, 'November to April', 165000.00, 'INR', 3.2027590, 73.2207390,
 'Beach,Luxury,Honeymoon,Island,Diving', b'1', b'1',
 UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 'system', 'system', 0),

('Dubai', 'dubai', 'United Arab Emirates', 'Dubai', 'Emirate of Dubai', 'Asia',
 'Desert dunes, record-breaking towers and a skyline that reinvents itself yearly.',
 'Dubai compresses a century of ambition into a single skyline. Ride to the observation deck of the Burj Khalifa, then trade the glass towers for the wooden abras of Dubai Creek and the spice-heavy lanes of Deira. Evenings belong to the desert: dune drives, falconry at golden hour, and dinner under a sky with no light pollution for miles.',
 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1920&q=80',
 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=80',
 4.70, 3204, 94, 'November to March', 95000.00, 'INR', 25.2048493, 55.2707828,
 'City,Luxury,Shopping,Desert,Family', b'1', b'1',
 UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 'system', 'system', 0),

('Paris', 'paris', 'France', 'Paris', 'Ile-de-France', 'Europe',
 'Boulevards, ateliers and the most photographed silhouette in the world.',
 'Paris rewards wandering more than itineraries. Cross the Seine at dusk when the Eiffel Tower begins its hourly sparkle, spend a slow morning with the Impressionists at the Musee d Orsay, and let the afternoon dissolve into the bakeries and bookshops of Saint-Germain. Montmartre still keeps its village pace, and the city has quietly become one of Europe''s best places to eat.',
 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1920&q=80',
 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80',
 4.80, 4102, 93, 'April to June, September to October', 130000.00, 'INR', 48.8566140, 2.3522219,
 'City,Culture,Romance,Food,Art', b'1', b'1',
 UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 'system', 'system', 0),

('Agra', 'agra', 'India', 'Agra', 'Uttar Pradesh', 'Asia',
 'Home of the Taj Mahal, and a Mughal capital worth far more than one morning.',
 'Most travellers give Agra a sunrise and leave. Stay longer. The Taj Mahal is genuinely worth the queue, its marble shifting from rose to white to amber over a single morning, but Agra Fort tells the harder story of the emperor who built it and died watching it from a cell. Cross the Yamuna to Mehtab Bagh at dusk, and the crowds disappear entirely.',
 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1920&q=80',
 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=800&q=80',
 4.70, 5310, 92, 'October to March', 22000.00, 'INR', 27.1766701, 78.0080745,
 'Heritage,Culture,Family,Budget', b'1', b'1',
 UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 'system', 'system', 0),

('Jaipur', 'jaipur', 'India', 'Jaipur', 'Rajasthan', 'Asia',
 'The Pink City: hilltop forts, stepwells and Rajasthan at its most theatrical.',
 'Jaipur was planned as a city of colour and still behaves like one. Amber Fort climbs the ridge above a lake, Hawa Mahal presents its honeycomb facade to the bazaar below, and Jantar Mantar turns astronomy into architecture. The old city remains a working marketplace of block printers, gem cutters and sweet shops that have not changed hands in generations.',
 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1920&q=80',
 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=800&q=80',
 4.60, 3890, 88, 'October to March', 26000.00, 'INR', 26.9124336, 75.7872709,
 'Heritage,Culture,Shopping,Family,Budget', b'1', b'1',
 UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 'system', 'system', 0),

('Tokyo', 'tokyo', 'Japan', 'Tokyo', 'Kanto', 'Asia',
 'Neon canyons, 400-year-old shrines and the best food city on the planet.',
 'Tokyo runs on contrast. Shibuya Crossing empties and refills every ninety seconds while, ten minutes away, Meiji Shrine sits in forest silence. Eat standing at a Tsukiji counter, ride the Yamanote line until a neighbourhood looks interesting, and finish in a six-seat Golden Gai bar. Spring cherry blossom and autumn maple are spectacular, but the city never has an off season.',
 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1920&q=80',
 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=800&q=80',
 4.90, 3671, 91, 'March to May, October to November', 145000.00, 'INR', 35.6761919, 139.6503106,
 'City,Culture,Food,Shopping,Nightlife', b'1', b'1',
 UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 'system', 'system', 0),

('Singapore', 'singapore', 'Singapore', 'Singapore', 'Central', 'Asia',
 'A garden city where hawker stalls hold Michelin stars and airports have waterfalls.',
 'Singapore proves a city can be engineered without losing character. Gardens by the Bay lights its supertrees each night, the Jewel at Changi drops a seven-storey waterfall inside a terminal, and a ten-minute walk takes you from colonial shophouses to Little India. The hawker centres are the real attraction: some of the best food in Asia, at a few dollars a plate.',
 'https://images.unsplash.com/photo-1555217851-6141535bd771?auto=format&fit=crop&w=1920&q=80',
 'https://images.unsplash.com/photo-1555217851-6141535bd771?auto=format&fit=crop&w=800&q=80',
 4.70, 2455, 87, 'February to April', 105000.00, 'INR', 1.3520830, 103.8198360,
 'City,Family,Food,Shopping,Modern', b'0', b'1',
 UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 'system', 'system', 0),

('Venice', 'venice', 'Italy', 'Venice', 'Veneto', 'Europe',
 'One hundred and eighteen islands, no cars, and light that has kept painters busy for centuries.',
 'Venice is best understood on foot and by accident. Leave the Rialto and San Marco to the day trippers and lose yourself in Cannaregio or Dorsoduro, where laundry crosses the canals and the bacari serve cicchetti until late. Take the vaporetto to Burano for its painted houses, and be on the water at sunrise at least once.',
 'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?auto=format&fit=crop&w=1920&q=80',
 'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?auto=format&fit=crop&w=800&q=80',
 4.80, 2988, 89, 'April to June, September to October', 125000.00, 'INR', 45.4408474, 12.3155151,
 'Culture,Romance,Heritage,Food', b'1', b'1',
 UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 'system', 'system', 0),

('Cinque Terre', 'cinque-terre', 'Italy', 'La Spezia', 'Liguria', 'Europe',
 'Five pastel villages stacked above the Ligurian Sea, linked by cliff paths.',
 'Cinque Terre is five fishing villages that never got around to modernising, which is precisely the appeal. The Sentiero Azzurro links them along the cliffs, with vineyards on terraces so steep they are worked by monorail. Swim off the rocks at Vernazza, eat trofie al pesto where it was invented, and take the last train back as the villages light up.',
 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=1920&q=80',
 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=800&q=80',
 4.70, 1633, 84, 'May to September', 118000.00, 'INR', 44.1461250, 9.6544230,
 'Coastal,Hiking,Romance,Food', b'0', b'1',
 UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 'system', 'system', 0),

('Swiss Alps', 'swiss-alps', 'Switzerland', 'Interlaken', 'Bernese Oberland', 'Europe',
 'Turquoise alpine lakes, cog railways and peaks that stay white all summer.',
 'The Alps are Europe''s great outdoor room. Base yourself in Interlaken or Lauterbrunnen and let the mountain railways do the work: Jungfraujoch for the glacier, Schynige Platte for the ridge walk, Grindelwald for everything else. In summer the valleys fill with wildflowers and waterfalls; in winter the same slopes become some of the most reliable skiing anywhere.',
 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1920&q=80',
 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=80',
 4.90, 2210, 90, 'June to September, December to March', 175000.00, 'INR', 46.6863200, 7.8632100,
 'Mountains,Adventure,Nature,Luxury,Hiking', b'1', b'1',
 UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 'system', 'system', 0),

('Banff', 'banff', 'Canada', 'Banff', 'Alberta', 'North America',
 'Glacier-fed lakes in improbable colours, ringed by the Canadian Rockies.',
 'Banff National Park earns its reputation within an hour of arriving. Moraine Lake and Lake Louise hold a blue that photographs badly because nobody believes it, fed by rock flour from the glaciers above. Drive the Icefields Parkway to Jasper, walk the Johnston Canyon catwalks, and watch for elk on the road at dusk.',
 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=1920&q=80',
 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=800&q=80',
 4.80, 1489, 85, 'June to September', 190000.00, 'INR', 51.1783979, -115.5708220,
 'Mountains,Nature,Adventure,Hiking,Wildlife', b'0', b'1',
 UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 'system', 'system', 0),

('London', 'london', 'United Kingdom', 'London', 'Greater London', 'Europe',
 'Two thousand years of history, world-class museums, and most of them free.',
 'London is really a collection of villages that agreed to share a transport network. Spend a morning in the British Museum, an afternoon along the South Bank, and an evening in a Soho theatre. Borough Market handles lunch, Hampstead Heath handles the hangover, and the National Gallery, Tate Modern and V&A cost nothing to enter.',
 'https://images.unsplash.com/photo-1533929736458-ca588d08c8be?auto=format&fit=crop&w=1920&q=80',
 'https://images.unsplash.com/photo-1533929736458-ca588d08c8be?auto=format&fit=crop&w=800&q=80',
 4.60, 3877, 86, 'May to September', 140000.00, 'INR', 51.5072178, -0.1275862,
 'City,Culture,Heritage,Shopping,Family', b'0', b'1',
 UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 'system', 'system', 0),

('Cape Town', 'cape-town', 'South Africa', 'Cape Town', 'Western Cape', 'Africa',
 'A flat-topped mountain, two oceans and vineyards forty minutes from the city.',
 'Few cities have Cape Town''s geography. Table Mountain rises straight out of the centre, the Cape Peninsula runs south to where the Atlantic and Indian oceans meet, and the Winelands of Stellenbosch and Franschhoek sit an easy drive inland. Add penguins at Boulders Beach and one of the most interesting food scenes in Africa.',
 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=1920&q=80',
 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=800&q=80',
 4.70, 1721, 83, 'November to March', 120000.00, 'INR', -33.9248685, 18.4240553,
 'Coastal,Nature,Adventure,Food,Wildlife', b'0', b'1',
 UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 'system', 'system', 0),

('Phuket', 'phuket', 'Thailand', 'Phuket', 'Southern Thailand', 'Asia',
 'Limestone islands, temple gold and the Andaman Sea at bath temperature.',
 'Phuket is the gateway to the Andaman rather than the destination itself. Use it as a base: longtail out to Phang Nga Bay''s limestone stacks, day-trip to the Similan Islands for the diving, and retreat to the quieter north of the island when Patong gets loud. Inland, Wat Chalong and the Big Buddha are worth the ride up.',
 'https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=1920&q=80',
 'https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=800&q=80',
 4.50, 2640, 82, 'November to April', 62000.00, 'INR', 7.8804479, 98.3922504,
 'Beach,Island,Budget,Nightlife,Diving', b'0', b'1',
 UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), 'system', 'system', 0);
